### PR TITLE
a11y: allow users to tab across the search button (and release: v2.8.6)

### LINKED ISSUE #198: A11y: Search bar triggers search when the search button is focused
Package version (if known): v12.0.0b3.dev3

## Describe the bug
If navigation the page with a keyboard, as soon as the search button gets focused the search is triggered.

## Steps to Reproduce
1. Go to any page containing the MultipleOptionsSearchBar
2. Press TAB couple of times to focus the search bar
3. As soon as you focus the search button with the next TAB input, the search is triggered.

## Expected behavior
When the search button is focused, the search should only be triggered by pressing the SPACE or ENTER buttons.

## Additional context
This bug prevents keyboard/screen reader users to navigate the page past the search bar. 

I think it has to do with this [handleFocus event listener](https://github.com/jennur/invenio-search-ui/blob/5d07b4153cd87b86ae7a4abaa8705d181fd5bd77/invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/MultipleOptionsSearchBar.js#L135-L138)

### PR DESCRIPTION
**Pull request by carlinmack**
:heart: Thank you for your contribution!

Close #198

### Description

> Please describe briefly your pull request.

Fix https://github.com/zenodo/rdm-project/issues/634

Previously as soon as you select the search button via tab it would execute the search. Now we only look for onMouseDown.

We cannot use onClick because the button moves as soon as it is focused via mouse down.

The behaviour is now:

* The button will search with a single `click`
* The button will search with `enter` or `spacebar`
* The input will search if the user presses `enter`
#### Video:

https://github.com/inveniosoftware/invenio-search-ui/assets/6676843/961dbcdb-8585-412f-8937-79d6ed9db0c4

> Description: I tab across the interface and use shift tab to go back to the search box. I then select the search button and press enter to search

https://github.com/inveniosoftware/invenio-search-ui/assets/6676843/66fa8b52-4a2b-4066-aa80-1e432fb1c6ff

> Description: Single clicking on the button and single clicking on the expanded search button both result in navigating to the search results

### Checklist

Ticks in all boxes and 🟢 on all GitHub actions status checks are required to merge:

- [x] I'm aware of the [code of conduct](https://inveniordm.docs.cern.ch/contribute/code-of-conduct/).
- [x] I've created [logical separate commits](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#commits) and followed the [commit message format](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#commit-message).
- [x] I've added relevant test cases.
- [x] I've added relevant documentation.
- [x] I've marked [translation strings](https://inveniordm.docs.cern.ch/develop/best-practices/i18n/) (for relevant code).
- [x] I've followed the [CSS/JS](https://inveniordm.docs.cern.ch/develop/best-practices/css-js/) and [React](https://inveniordm.docs.cern.ch/develop/best-practices/react/) guidelines (for relevant code).
- [x] I've followed the [web accessibility](https://inveniordm.docs.cern.ch/develop/best-practices/accessibility/) guidelines (for relevant code).
- [x] I've followed the [user interface](https://inveniordm.docs.cern.ch/develop/best-practices/ui/) guidelines (for relevant code).
- [x] I've identified the [copyright holder(s)](https://inveniordm.docs.cern.ch/contribute/copyright-policy/) and updated copyright headers for touched files (>15 lines contributions).
- [x] I've NOT included third-party code (copy/pasted source code or new dependencies).

**Third-party code**

If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).

**Reminder**

By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:

1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you have the right to license your contribution under the current repository’s license.

### CODE REVIEW

**Review by ptamarit — APPROVED** [review]
# Code review

:heavy_check_mark: Using `onMouseDown` is definitely weird, but this is a symptom of the auto-expanding text field, and it is properly comment.

# Testing

Tested locally with InvenioRDM version `12.0.0b3.dev9` (and with the latest changes in this repo until `v2.8.5` included).

Keyboard and search button:

* Going to: https://127.0.0.1:5000/search
* 3x tab to reach text field
* Typing some search text
* 1x tab to focus on submit button
* :heavy_check_mark: The form is *not* submitted
* 1x tab to reach "Communities"
* 1x shift-tab to focus on the submit button
* Typing Enter
* :heavy_check_mark: The form *is* submitted

Keyboard and text field:

* Going to: https://127.0.0.1:5000/search
* 3x tab to reach text field
* Typing some search text
* Typing Enter
* :heavy_check_mark: The form *is* submitted

Mouse and search button:

* Going to: https://127.0.0.1:5000/search
* Clicking on the text field
* Typing some search text
* Clicking on the search button
* :heavy_check_mark: The form *is* submitted

File: invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/MultipleOptionsSearchBar.js [hunk 1]
```diff
@@ -158,7 +149,6 @@ export class MultipleOptionsSearchBarCmp extends Component {
         onResultSelect={this.onBtnSearchClick}
         onSearchChange={this.handleOnSearchChange}
         resultRenderer={(props) => resultRenderer(props, queryString)}
-        onFocus={this.handleFocus}
```
Comment (kpsherva) [inline invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/MultipleOptionsSearchBar.js:161]: if we remove onFocus, can we still navigate to the searchbar by using tab? (I think it could matter for accessibility as well - screen readers, but correct me if I am wrong)

Comment (ptamarit) [reply invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/MultipleOptionsSearchBar.js:161]: Yes, one can reach the search bar with tab (see my keyboard tests above).
What this handler was doing was to submit the form when the button received focused, which is clearly not a behavior we want (it's probably that people tested the previous change with the mouse only).

**Comment by ptamarit** [comment]
Pushed the tag and released on PyPI: https://pypi.org/project/invenio-search-ui/2.8.6/
